# Generated by Django 3.0.7 on 2020-06-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_items',
            new_name='items',
        ),
    ]
