# Generated by Django 3.0.7 on 2020-06-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200609_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='completed',
            new_name='ordered',
        ),
    ]
