# Generated by Django 3.0.7 on 2020-06-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orderitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='ordered',
        ),
    ]
