# Generated by Django 3.0.7 on 2020-06-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200609_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='items',
        ),
    ]
